unique_ids:
  forms:
    Symmetrie: BMN3YLQMZK5RBLV2YWA6IOTQ7XD4GFTI
  modules: {}
  server_modules: {}
  assets:
    standard-page.html: EWYQ4SKWMTBO47BUVDRNX3W3D5WT7NHL
    symmetrie.png: '1695706085454918188689761.8062'
    theme.css: 74Q6NKQOA7GCJYX5ZULDPEKTQ27ZKDDL
